name: kamma
description: Native LLM models for Dart. Run popular pipelines like Gemma, GPT, Deepseek, etc.
version: 1.0.0
repository: https://github.com/tejainece/kamma

environment:
  sdk: ^3.11.0-93.1.beta

# Add regular dependencies here.
dependencies:
  tensor:
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

dependency_overrides: 
  tensor: 
    path: ../tensor

